version: '3'
services:
  client:
    build: ./client
    restart: always
    volumes:
    - ./client:/opt/app
    - /opt/app/node_modules
    ports:
    - 8080:8080
    links:
    - server

  server:
    build: ./server
    restart: always
    volumes:
    - ./server:/opt/app
    - /opt/app/node_modules
    ports:
    - 5000
